### ISSUE TITLE
请问下如果我要改造成这种目录结构该怎么处理呢？

### ISSUE THREAD

**Issue by Loinver** [bigmeow/vue-cli-multipage-template#1]
![image](https://user-images.githubusercontent.com/8012098/38873841-4cd93a12-4289-11e8-9119-93bcb4bdf75b.png)
如图，所有的文件夹都是a这种的

**Comment by Loinver** [comment]
额  处理成功了，但还是有一个多页面的通病   页面多了之后  
![image](https://user-images.githubusercontent.com/8012098/38936275-076406ae-4353-11e8-97f5-8f5493d342b5.png)
94% asset optimization到done   中间间隔时间太长了，这个不知道咋解决了

**Comment by bigmeow** [comment]
我在Mac上挺快的...

**Comment by Loinver** [comment]
我这是假定25个文件夹  每个文件夹内2个theme文件夹   也就是50个页面，总的随便修改一个字符   编译时间就会等25s左右

**Comment by bigmeow** [comment]
竟然这么慢 ，没法用啊 ，周末我看看源码测试一下，看看能不能改下，只编译改动的文件，这情况有点像所有的多页都重新编译了

**Comment by bigmeow** [comment]
https://stackoverflow.com/questions/49184787/92-chunk-asset-optimization-webpack
https://juejin.im/entry/598bcbc76fb9a03c5754d211

这两个可以解决这问题  你先试一下  我周末再弄  再交流

**Comment by Loinver** [comment]
好的  谢谢
